name: macos_arm

on:
  push:
    tags:
      - "20*"

jobs:
  build:
    runs-on: "macos-latest"
    
    env:
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      MACOSX_DEPLOYMENT_TARGET: "10.12"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: "Install Rust (ARM)"
        shell: bash
        run: "rustup target add aarch64-apple-darwin"
      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Vendor dependecies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: "cargo vendor --locked --versioned-dirs >> .cargo/config"
      - name: "Install System Deps"
        shell: bash
        run: "env CI=yes PATH=$PATH ./get-deps"
      - name: "Build wezterm (Release mode ARM)"
        shell: bash
        run: "cargo build -p wezterm -p wezterm-gui -p strip-ansi-escapes --release"
      - name: "Package"
        shell: bash
        run: "bash ci/deploy.sh"
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "macos"
          path: |
            WezTerm-*.zip
            wezterm.rb
          retention-days: 5

  upload:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'I-Info/wezterm'
    permissions:
      contents: write

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: "macos"
      - name: "Checkout homebrew tap"
        uses: actions/checkout@v4
        with:
          repository: "I-Info/homebrew-beer"
          path: "homebrew"
          token: "${{ secrets.GH_PAT }}"
      - name: "Update homebrew tap formula"
        shell: bash
        run: "cp wezterm.rb homebrew/Casks/wezterm.rb"
      - name: "Commit homebrew tap changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update WezTerm to match latest tag"
          repository: "homebrew"
      - name: "Checksum"
        shell: bash
        run: "for f in WezTerm-*.zip ; do sha256sum $f > $f.sha256 ; done"
      - name: "Create pre-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh bash ci/create-release.sh $(ci/tag-name.sh)"
      - name: "Upload to Tagged Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: "bash ci/retry.sh gh release upload --clobber $(ci/tag-name.sh) WezTerm-*.zip *.sha256"
